services:
  gotenberg:
    image: gotenberg/gotenberg:8
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8123:80"
    depends_on:
      - gotenberg
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
